services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: NESTRS
    volumes:
      - ./postgres:/var/lib/postgresql/data